export const catchError = e => {
    console.log(e);
    alert(e)
}